# Form implementation generated from reading ui file '/Users/grantpeters/Documents/CSII_project_1/gui_ballot.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 400)
        MainWindow.setMinimumSize(QtCore.QSize(300, 400))
        MainWindow.setMaximumSize(QtCore.QSize(300, 400))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ballot_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.ballot_label.setGeometry(QtCore.QRect(100, 5, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.ballot_label.setFont(font)
        self.ballot_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ballot_label.setObjectName("ballot_label")
        self.blue_radio_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.blue_radio_button.setGeometry(QtCore.QRect(110, 70, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.blue_radio_button.setFont(font)
        self.blue_radio_button.setObjectName("blue_radio_button")
        self.radio_group = QtWidgets.QButtonGroup(MainWindow)
        self.radio_group.setObjectName('radio_group')
        self.radio_group.addButton(self.blue_radio_button)
        self.red_radio_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.red_radio_button.setGeometry(QtCore.QRect(110, 110, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.red_radio_button.setFont(font)
        self.red_radio_button.setObjectName("red_radio_button")
        self.radio_group.addButton(self.red_radio_button)
        self.green_radio_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.green_radio_button.setGeometry(QtCore.QRect(100, 150, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.green_radio_button.setFont(font)
        self.green_radio_button.setObjectName("green_radio_button")
        self.radio_group.addButton(self.green_radio_button)
        self.cast_vote_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.cast_vote_button.setGeometry(QtCore.QRect(20, 180, 120, 30))
        self.cast_vote_button.setObjectName("cast_vote_button")
        self.end_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.end_button.setGeometry(QtCore.QRect(160, 180, 120, 30))
        self.end_button.setObjectName("end_button")
        self.results_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.results_label.setGeometry(QtCore.QRect(80, 220, 141, 91))
        self.results_label.setText("")
        self.results_label.setObjectName("results_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ballot_label.setText(_translate("MainWindow", "Ballot"))
        self.blue_radio_button.setText(_translate("MainWindow", "Blue"))
        self.red_radio_button.setText(_translate("MainWindow", "Red"))
        self.green_radio_button.setText(_translate("MainWindow", "Green"))
        self.cast_vote_button.setText(_translate("MainWindow", "Cast Vote"))
        self.end_button.setText(_translate("MainWindow", "End"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
